Single Resort Backend
underflip/shredindex-backend pull request #21
Opened 2021-05-30 10:11 UTC by Krank3n

Includes location plugin + model

2021-05-30 10:30 UTC, jakxnz requested changes
Hey hey hey. Look who's shown up at the full-stack game! Nice to see. I don't see any glaring issues, just raised a few minor questions and suggestions. Digging it.

2021-05-30 10:30 UTC, jakxnz commented on graphql/headstart/graphs/resorts.htm
> +    id: Int
Can we keep this as `ID`? Seems odd to go against such a case-specific datatype, created specifically for this use.

2021-05-30 10:30 UTC, jakxnz commented on graphql/headstart/graphs/resorts.htm
> +    country: LocationItem! @hasOne
Is this a good place to follow the same convention we used for attributes, and make separate schama types for `country` and `state`?

2021-05-30 10:30 UTC, jakxnz commented on plugins/underflip/resorts/controllers/resorts/resorts_form.yaml
> +    title: Edit a Resort
This seems like an odd diff, does this need to be in the commit?

2021-05-30 10:30 UTC, jakxnz commented on graphql/headstart/graphs/resorts.htm
> +type LocationType {
Could we name this after the model it represents? i.e `Location`?

2021-05-30 10:30 UTC, jakxnz commented on plugins/underflip/resorts/models/Location.php
> +class Location extends Model
Could you docBlock the `@property`s and `@method`s available to this model?

2021-05-30 10:30 UTC, jakxnz commented on plugins/underflip/resorts/models/location/fields.yaml
> +
```suggestion
```

2021-05-30 10:30 UTC, jakxnz commented on plugins/underflip/resorts/models/Location.php
> +
```suggestion
```

2021-05-30 10:30 UTC, jakxnz commented on plugins/underflip/resorts/updates/create_location_table.php
> +        });
```suggestion
        Schema::create(app(Location::class)->getTable(), function ($table) {
            $table->increments('id');
            $table->integer('resort_id')->nullable();
            $table->string('address')->nullable();
            $table->string('city')->nullable();
            $table->string('zip')->nullable();
            $table->integer('country_id')->nullable();
            $table->integer('state_id')->nullable();
            $table->decimal('latitude')->nullable();
            $table->decimal('longitude')->nullable();
            $table->string('vicinity')->nullable();
        });
```

2021-05-30 10:30 UTC, jakxnz commented on plugins/underflip/resorts/updates/create_location_table.php
> +        });
Do we want so much of this to be nullable? In cases like this, it's generally better to start strict and remove restrictions when there's a clear case for them. `state_id` seems like it could be nullable, but is there a case where a location would ever not have the other values?

2021-05-30 10:30 UTC, jakxnz commented on plugins/underflip/resorts/updates/create_resorts_table.php
> +            $table->string('description')->unique();
```suggestion
            $table->string('description');
```

2021-05-30 10:30 UTC, jakxnz commented on graphql/headstart/graphs/resorts.htm
> +    name: String
```suggestion
    id: ID!
    code: String!
    name: String!
```

These all seem non-nullable.

Also, I see that I haven't done the same for what used to be the `ResortAttribute` type, reckon you could tidy those up too? (Sorry)

2021-05-30 21:16 UTC, Krank3n commented on plugins/underflip/resorts/updates/create_location_table.php
> +        });
changed

2021-05-30 21:19 UTC, Krank3n commented on graphql/headstart/graphs/resorts.htm
> +    name: String
Sure, i left the Zip code in the location model nullable, as I remember putting some address in and it wasnt populating, could end up being a headache.

2021-05-30 22:19 UTC, jakxnz requested changes

2021-05-30 22:19 UTC, jakxnz commented on plugins/underflip/resorts/models/Location.php
> +    * @property string vicinity
Generally you don't need to docBlock a relation id, unless it's being used explicitly. DocBlock the relation instead, i.e

Instead of `@property int resort_id` we can use `@property Resort $resort` or `@method Resort resort()` depending on its use. I generally start by adding the `@method` and then add the `@property` when I explicitly want to call it.

2021-05-30 22:19 UTC, jakxnz commented on plugins/underflip/resorts/models/Location.php
> +     * @var The database table used by the model.
If you're annotating `@vars`, you need to provide a data type

```
@var string The database table used by the model.
```

2021-05-30 22:19 UTC, jakxnz commented on plugins/underflip/resorts/updates/create_location_table.php
> +                    $table->string('address')();
Does this code even work 😅?

These need to be like:
```
$table-> string('address');
```

2021-05-30 22:19 UTC, jakxnz commented on plugins/underflip/resorts/updates/create_resorts_table.php
> +            $table->string('description')();
Does this code even work 😅?

These need to be like:
```
$table-> string('description');
```

2021-06-01 09:47 UTC, Krank3n commented on plugins/underflip/resorts/updates/create_resorts_table.php
> +            $table->string('description')();
haha... hope I am aloud ot laugh at this

2021-06-01 09:48 UTC, Krank3n commented on plugins/underflip/resorts/updates/create_location_table.php
> +                    $table->string('address')();
fixed

2021-06-01 09:52 UTC, Krank3n commented on plugins/underflip/resorts/models/Location.php
> +     * @var The database table used by the model.
what is the data type, if its a table? A string? Why?

2021-06-01 09:55 UTC, Krank3n commented on plugins/underflip/resorts/controllers/resorts/resorts_form.yaml
> +    title: Edit a Resort
Did I add this? I'll remove it, maybe I did. geeze.

2021-06-01 10:16 UTC, jakxnz commented on plugins/underflip/resorts/models/Location.php
> +     * @var The database table used by the model.
DocBlocks annotations are PHP's way of filling in the gaps, because the language is loosely typed. So, generally when you annotate something with DocBlock `@` annotations, it's so that you can introduce meaning for the IDE to assist with developing the language, to do things like warning the user if they're assigning a `Table` class to a property that is supposed to be the `string` name of a MySQL table. That's what the `@var` annotation is for. It's not so much for describing the property. In fact, in this scenario...

```
/**
 * @var string
 */
 ```
 
 ... would be totally sufficient because the property describes itself for anyone familiar with Laravel/October CMS.

2021-06-01 10:23 UTC, jakxnz requested changes
This is pretty much there. I noticed two super minor things and will wait until you've got the unit tests passing before I do a manual test 👍

2021-06-01 10:23 UTC, jakxnz commented on plugins/underflip/resorts/updates/create_location_table.php
> +        });
Is it just me, or is this indentation still out?

2021-06-01 10:23 UTC, jakxnz commented on plugins/underflip/resorts/models/resort/fields.yaml
> +        label: 'Description'
Interesting time to suddenly start encapsulating with `'`s 😅

2021-06-06 02:58 UTC, Krank3n commented on plugins/underflip/resorts/models/resort/fields.yaml
> +        label: 'Description'
Think I copied your 'URL Segment'? Maybe anyway changed both back.

2021-06-06 02:59 UTC, Krank3n commented on plugins/underflip/resorts/updates/create_location_table.php
> +        });
Not much gets past you 👯‍♂️

2021-06-07 02:46 UTC, jakxnz reviewed
The code is looking good! I'll wait for the unit tests to be passing before I manually test 👍

2021-06-20 07:27 UTC, jakxnz requested changes
I had a few questions about comment stuff. Will start doing some manual tests 👍

2021-06-20 07:27 UTC, jakxnz commented on plugins/underflip/resorts/models/Location.php
> +    * A location resort attribute for resort location that are
What's up with the nesting here?

2021-06-20 07:27 UTC, jakxnz commented on plugins/underflip/resorts/models/Location.php
> +     * @var Location plugin used by the model.
Could this just be `@var array`?

2021-06-20 07:27 UTC, jakxnz commented on plugins/underflip/resorts/models/Resort.php
> -     */
You removed the docBlock(s)?

2021-06-20 08:55 UTC, Krank3n commented on plugins/underflip/resorts/models/Location.php
> +    * A location resort attribute for resort location that are
Good question, how do I indent only one space, as opposed to a full (one hit tab) space

2021-06-20 08:58 UTC, Krank3n commented on plugins/underflip/resorts/models/Resort.php
> -     */
why would I do that

2021-07-04 02:33 UTC, jakxnz commented on plugins/underflip/resorts/models/Location.php
> +    * A location resort attribute for resort location that are
Yeah, just hit space

2021-07-04 02:34 UTC, jakxnz approved these changes
LGTM

2021-07-04 02:47 UTC, merged