Added Resort Images and Comments
underflip/shredindex-backend pull request #26
Opened 2021-10-26 09:34 UTC by Krank3n

Resort Plugin additional Images and Comments fields

2021-12-23 00:45 UTC, jakxnz requested changes
This is a really well-sized changeset! It suggests the scope of the front-end changes are a good set. This looks like it's in the right direction, just a few questions and suggestions from me

2021-12-23 00:45 UTC, jakxnz commented on plugins/underflip/resorts/models/Resort.php
> +     }
```suggestion
     /**
      * The "total score" that represents all ratings of this resort
      *
      * @return Rating
      */
     public function getTotalScoreAttribute()
     {
         $values = $this->ratings()->pluck('value');
     
         $rating = new Rating();
         $rating->name = Rating::RATING_NAME_TOTAL_SCORE;
         $rating->title = __('Total score');
         $rating->value = round(array_sum($values)/count($values), 1);
     
         return $rating;
     }
```

2021-12-23 00:45 UTC, jakxnz commented on plugins/underflip/resorts/models/Resort.php
> +        ->get();
```suggestion
          ->orderBy('value', 'desc')
          ->limit(3)
          ->get();
```

2021-12-23 00:45 UTC, jakxnz commented on plugins/underflip/resorts/models/Resort.php
> +        ->get();
```suggestion
          ->orderBy('value', 'asc')
          ->limit(3)
          ->get();
```

2021-12-23 00:45 UTC, jakxnz commented on plugins/underflip/resorts/updates/create_resort_images_table.php
> +                $resort_image->image->delete();
❤️

2021-12-23 00:45 UTC, jakxnz commented on plugins/underflip/resorts/updates/create_resorts_table.php
> +            $table->string('url')->unique();
Do we need to store this in the db? (It's generally not a good idea to store URLs in a database)

2021-12-23 00:45 UTC, jakxnz commented on plugins/underflip/resorts/updates/create_resorts_table.php
> +            $table->decimal('total_score');
Is this needed? (I thought total score was being generated dynamically?)

2021-12-23 00:45 UTC, jakxnz commented on plugins/underflip/resorts/updates/version.yaml
> +1.0.2:
We don't need a `1.0.2`, the only reason we use the sem ver convention is that October doesn't work without it. We'll start incrementing this once we have something in production. Just pile on `1.0.1`

2021-12-23 02:10 UTC, Krank3n commented on plugins/underflip/resorts/updates/create_resorts_table.php
> +            $table->string('url')->unique();
Ohhh that does sound familiar, thanks for mentioning this.

2022-01-31 20:48 UTC, jakxnz commented on plugins/underflip/resorts/models/Resort.php
> +        }
```suggestion
        $score = is_array($values)
            ? round(array_sum($values)/count($values), 1);
            : 0;
```

This does make me think... What _do_ we want as the fallback for if there's ever a resort with no ratings? Do we want its total score to be an arbitrary amount? Or do we actually want to label it "Unscored" or something? Maybe if there's no ratings, this method should just return `null`, to indicate it doesn't have a total score?

2022-01-31 20:51 UTC, jakxnz requested changes
Almost there!

2022-01-31 20:51 UTC, jakxnz commented on graphql/headstart/graphs/resorts.htm
> +    total_score: String!
Should this be a `Rating` type?

2022-02-01 20:32 UTC, jakxnz commented on plugins/underflip/resorts/models/Resort.php
> +        }
Have addressed this in https://github.com/underflip/shredindex-backend/pull/27

2022-02-01 20:32 UTC, jakxnz commented on graphql/headstart/graphs/resorts.htm
> +    total_score: String!
Have altered this in https://github.com/underflip/shredindex-backend/pull/27

2022-02-01 23:52 UTC, jakxnz commented
@Krank3n I've merged https://github.com/underflip/shredindex-backend/pull/27 into this branch. Could you please give this branch a final check over, and let me know if it's ready?

2022-02-13 00:55 UTC, jakxnz requested changes
TIL

2022-02-13 00:55 UTC, jakxnz commented on plugins/underflip/resorts/Plugin.php
> +        $schedule->command('resorts:refresh_total_score')->hourly();
I've since learned that we probably want to use a Model Observer to do this instead (https://laravel.com/docs/8.x/eloquent#observers), that way it will update in real-time. I'll make a change request here, and raise a change suggestion for this PR as soon as I can

2022-03-03 08:40 UTC, jakxnz commented
I have rebased this branch, and also moved the total score refresh away from a schedule and into an observer event. You can find more details in the updated docs.

2022-03-03 22:19 UTC, jakxnz requested changes
Leaving a change request for myself

2022-03-03 22:19 UTC, jakxnz commented on plugins/underflip/resorts/database/seeders/ResortsSeeder.php
>                  $rating->value = rand(0, 100);
Can we add some weighting, to achieve a wider distribution of total scores?

2022-03-03 23:16 UTC, Krank3n commented on plugins/underflip/resorts/updates/create_comments_table.php
> +            $table->text('comment');
Nice bro

2022-03-04 03:18 UTC, jakxnz commented on plugins/underflip/resorts/database/seeders/ResortsSeeder.php
>                  $rating->value = rand(0, 100);
> Will we want to add decimal values to some of the ratings?

Ratings are integers, so no decimals. That's part of why the `TotalScore` model doesn't extend the `Rating` model

2022-03-04 03:18 UTC, jakxnz commented on plugins/underflip/resorts/database/seeders/ResortsSeeder.php
>                  $rating->value = rand(0, 100);
> I was gonna ask do we want to also weight the random number of ratings?

What's the benefit to weighting the number of ratings?

2022-03-04 03:19 UTC, jakxnz commented on plugins/underflip/resorts/database/seeders/ResortsSeeder.php
> +            $imagesCount = rand(0, count($images)/2); // Make sure we don't exceed the available images
Yeah, it'll hit an un-sanity checked index error when the loop hits a higher number than there are images.

2022-03-04 10:22 UTC, jakxnz approved these changes
LGTM

2022-03-04 22:23 UTC, Krank3n commented on plugins/underflip/resorts/database/seeders/ResortsSeeder.php
>                  $rating->value = rand(0, 100);
Well it seemed to not show any resorts without any ratings at all.

2022-03-04 22:24 UTC, Krank3n commented
Good job man :)

2022-03-04 22:24 UTC, merged