Ranked Resorts Booking Affiliate URL
underflip/shredindex-backend pull request #34
Opened 2022-03-23 22:27 UTC by Krank3n

Added a booking affiliate URL
https://trello.com/c/fmQKZee3/11-ranked-resorts-component

2022-03-24 00:24 UTC, jakxnz requested changes
Looking good. A few things from me

2022-03-24 00:24 UTC, jakxnz commented on plugins/underflip/resorts/database/seeders/ResortsSeeder.php
> +            $resort->booking_affiliate_url = 'https://www.' . $resort->url_segment . '.com';
```suggestion
            $resort->booking_affiliate_url = sprintf('https://localhost/%s', $resort->url_segment);
```

It's usually a good idea not to construct lifelike URLs for testing, in case a local environment or a CI environment starts sending out traffic on that URL.

2022-03-24 00:24 UTC, jakxnz commented on graphql/headstart/graphs/resorts.htm
> +    booking_affiliate_url: String!
Could this just be `affiliate_url`? Affiliate URLs aren't always for booking.

2022-03-24 00:24 UTC, jakxnz commented on plugins/underflip/resorts/updates/create_resorts_table.php
> +            $table->string('booking_affiliate_url');
```suggestion
            $table->text('booking_affiliate_url');
```

Probably a good idea to give some extra ceiling room in case there's a very long affiliate URL (to accommodate an unknown amount of affiliate URL query params)

2022-03-24 09:19 UTC, Krank3n commented on plugins/underflip/resorts/updates/create_resorts_table.php
> +            $table->string('booking_affiliate_url');
Smart... :)

2022-03-24 09:20 UTC, Krank3n commented on graphql/headstart/graphs/resorts.htm
> +    booking_affiliate_url: String!
Yea true :)

2022-03-26 07:00 UTC, jakxnz approved these changes
LGTM 👍

2022-03-26 07:00 UTC, merged